service: ats-microservice

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  healthCheck:
    handler: handler.health_check
    events:
      - http:
          path: health
          method: get

  getJobs:
    handler: handler.get_jobs
    events:
      - http:
          path: jobs
          method: get
  createCandidate:
    handler: handler.create_candidate
    events:
      - http:
          path: candidates
          method: post
  getApplications:
    handler: handler.get_applications
    events:
      - http:
          path: applications
          method: get
